# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:46
from __future__ import unicode_literals

import badger.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text=b'Explanation and evidence for the badge award')),
                ('image', models.ImageField(blank=True, max_length=256, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=badger.models.UploadTo(b'image', b'png'))),
                ('claim_code', models.CharField(blank=True, db_index=True, default=b'', help_text=b'Code used to claim this award', max_length=32)),
                ('hidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified', '-created'],
            },
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Short, descriptive title', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text=b'Very short name, for use in URLs and links', unique=True)),
                ('description', models.TextField(blank=True, help_text=b'Longer description of the badge and its criteria')),
                ('image', models.ImageField(blank=True, help_text=b'Upload an image to represent the badge', max_length=256, null=True, upload_to=badger.models.UploadTo(b'image', b'png'))),
                ('unique', models.BooleanField(default=True, help_text=b'Should awards of this badge be limited to one-per-person?')),
                ('nominations_accepted', models.BooleanField(default=True, help_text=b'Should this badge accept nominations from other users?')),
                ('nominations_autoapproved', models.BooleanField(default=False, help_text=b'Should all nominations be automatically approved?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group_badge', models.NullBooleanField(default=False)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('badgeType', models.CharField(blank=True, choices=[(b'AS', 'Assignment'), (b'APP', 'Application'), (b'AT', 'Automatic')], default=b'', max_length=3, null=True)),
                ('assignment_badge', models.NullBooleanField(default=False, help_text=b'This badge accept direct assignments?')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, help_text=b'When all of the selected badges have been awarded, this badge will be automatically awarded.', to='badger.Badge')),
            ],
            options={
                'ordering': ['-modified', '-created'],
                'permissions': (('manage_deferredawards', 'Can manage deferred awards for this badge'),),
            },
        ),
        migrations.CreateModel(
            name='DeferredAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('reusable', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('claim_code', models.CharField(db_index=True, default=badger.models.make_random_code, max_length=32, unique=True)),
                ('claim_group', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badger.Badge')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified', '-created'],
                'permissions': (('grant_deferredaward', 'Can grant deferred award to an email address'),),
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('rejected_reason', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomination_approver', to=settings.AUTH_USER_MODEL)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='badger.Award')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badger.Badge')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomination_creator', to=settings.AUTH_USER_MODEL)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination_nominee', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomination_rejected_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0)),
                ('counter', models.FloatField(blank=True, default=0, null=True)),
                ('notes', badger.models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badger.Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Progresses',
            },
        ),
        migrations.AddField(
            model_name='award',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badger.Badge'),
        ),
        migrations.AddField(
            model_name='award',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='award',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set([('badge', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together=set([('title', 'slug')]),
        ),
    ]
